name: Publish Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: flathub-cache

jobs:
  docker_publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -   name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: |
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME}}
            tags: |
              type=sha,format=short,prefix=
      -
        name: Build and push Docker images
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME}}:latest
          labels: ${{ steps.meta.outputs.labels }}
          push: true
